-- drop table USER if exists;

-- CREATE TABLE USER (ID integer identity primary key,USERNAME varchar(20) NOT NULL, MOBILE varchar(20) not null, EMAIL varchar(50) default null, FULLNAME varchar(50) DEFAULT NULL, ROLE varchar(1) DEFAULT NULL, STATUS varchar(1) DEFAULT NULL, DATE_CREATED integer, DATE_UPDATED integer, unique(MOBILE));

-- CREATE SCHEMA OSNZ AUTHORIZATION DBA;

-- id                  BIGINT          generated by default as identity (start with 1),

-- CREATE SCHEMA OSNZ;

--CREATE SCHEMA IF NOT EXISTS OSNZ;

--CREATE SEQUENCE OSNZ.OSNZ_SEQUENCE START WITH 1 INCREMENT BY 1;

--CREATE SEQUENCE OSNZ.DEFAULT_CW_MEMBER START WITH 1 INCREMENT BY 1;

CREATE TABLE member (
  id                  INTEGER         IDENTITY PRIMARY KEY,
  email               VARCHAR(50)     DEFAULT NULL, 
  mobile              VARCHAR(20)     NOT NULL,
  password            VARCHAR(50)     NOT NULL,
  created_on          DATETIME        NOT NULL,
  updated_on          DATETIME        NOT NULL,
  date_verified_email DATETIME        DEFAULT NULL,
  verified_email      INT             NOT NULL,
  role                VARCHAR(50)     NOT NULL,
  credit_point        INTEGER         NOT NULL,
  pending_expense     DECIMAL(12, 2)  NOT NULL,
  total_expense       DECIMAL(12, 2)  NOT NULL,
  active              INT             NOT NULL
);
