sudo: false
language: java
jdk:
- oraclejdk11
branches:
  only:
  - master
before_install:
- unset GEM_PATH
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify install
cache:
  directories:
  - '$HOME/.m2/repository'
#    - '$HOME/.sonar/cache'
