sudo: false
language: java
jdk:
  - oraclejdk11
branches:
  only:
    - master
before_install:
  - unset GEM_PATH
install:
  - mvn -B -U -T4C clean dependency:tree
script:
  - mvn -B -U -T4C clean verify
    #cache:
    # directories:
  #- '$HOME/.m2/repository'
#    - '$HOME/.sonar/cache'
