sudo: false
language: java
jdk:
- oraclejdk11
branches:
  only:
  - master
before_install:
- unset GEM_PATH
script:
- mvn --version
- mvn -U -T2C clean verify
cache:
  directories:
  - '$HOME/.m2/repository'
#    - '$HOME/.sonar/cache'
