openapi: '3.0.0'

info:
  version: 1.0.0
  title: Hello world API
  description: Hello world API

servers:
  - url: http://localhost:9090/v1
    description: the endpoint for hello world APIs

tags:
  - name: Hello
    description: Everything about hello messages

paths:
  /hello:
    summary: hello
    description: >-
      Hello world
    get:
      operationId: hello
      tags:
        - Hello
      description: >-
        Welcome message
      parameters:
        - name: name
          in: query
          description: name
          required: false
          allowEmptyValue: true
          schema:
            type: string
      responses:
        '200':
          description: >-
            Reply hello message
          content:
            application/json:
              schema:
                type: string
