
### Server Settings
server:
  port: 9090

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false

camel:
  springboot:
    name: ServicesRest
  cloud:
    enabled: true
