name: Main Workflow

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    # Job name is verify
    name: Run
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup java 11
        uses: actions/setup-java@v1
        with:
          version: '11.0.4'
          architecture: x64

      - name: Check java version
        run: java --version

      - name: Check maven version
        run: mvn -version

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

#      - name: maven verify
#        run: mvn -U -T4C clean verify
#
#      - name: maven install
#        run: mvn -B install -DskipTests

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B -T4C clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

      # - name: sonarcloud
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     BRANCH_NAME: "master"
      #   run: |-
      #     mvn org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -q --batch-mode \
      #     -Dmaven.test.failure.ignore=true \
      #     -Dmaven.test.error.ignore=true \
      #     -Dsonar.login=$SONAR_TOKEN \
      #     -Dsonar.host.url=https://sonarcloud.io \
      #     -Dsonar.organization=kdeng \
      #     -Dsonar.projectKey=kdeng_java-collections \
      #     -Dsonar.branch.name=$BRANCH_NAME \
      #     -Dorg.slf4j.simpleLogger.showDateTime=true \
      #     -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS
